package: rex_redactor2
version: '2.1.1'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/rex_redactor2

page:
    title: 'translate:title'
    perm: rex_redactor2[]
    pjax: true
    subpages:
        profiles: { title: 'translate:profiles', perm: rex_redactor2[profiles] }