package: redactor2
version: '4.1.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/redactor2

page:
    title: 'translate:title'
    perm: redactor2[]
    pjax: true
    subpages:
        profiles: { title: 'translate:profiles', perm: redactor2[profiles] }
        help: { title: 'translate:help', icon: rex-icon fa-info-circle, itemclass: pull-right}

requires:
    redaxo: '^5.6'
    php:
        version: '>=5.6' # benötigt mindestens PHP 5.6
