package: redactor2
version: '2.2.4'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/redactor2

page:
    title: 'translate:title'
    perm: redactor2[]
    pjax: true
    subpages:
        profiles: { title: 'translate:profiles', perm: redactor2[profiles] }