package: redactor2
version: '3.6.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/redactor2

page:
    title: 'translate:title'
    perm: redactor2[]
    pjax: true
    subpages:
        profiles: { title: 'translate:profiles', perm: redactor2[profiles] }
        
requires:
    redaxo: '>=5.6'
    php:
        version: '>=5.6' # benötigt mindestens PHP 5.6
